{
 "title": "Uptimes",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "Type",
    "query": {
     "query": "label_values(monitor_response_time, monitor_type)"
    }
   },
   {
    "name": "Monitor",
    "query": {
     "query": "label_values(monitor_response_time{monitor_type=~\"$Type\"}, monitor_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(monitor_status) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(monitor_status == 1) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offline",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(monitor_status == 0) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": {
    "content": "## Tip!\n\nVisit [uptime.neiaac.com](https://uptime.neiaac.com) to add additional platforms to monitor here."
   }
  },
  { "title": "$Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }, "repeat": "Monitor" },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_status{monitor_name=~\"$Monitor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 18, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_response_time{monitor_name=~\"$Monitor\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "avg_over_time(monitor_response_time{monitor_name=~\"$Monitor\"}[24h])",
     "legendFormat": "24h"
    }
   ]
  },
  {
   "title": "Certificate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "monitor_cert_days_remaining{monitor_name=~\"$Monitor\"}",
     "legendFormat": "Days until expiration"
    }
   ]
  }
 ]
}